CREATE DATABASE IF NOT EXISTS english_everyday
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE english_everyday;

CREATE TABLE IF NOT EXISTS exam_year (
  year INT NOT NULL PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS section (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  year INT NOT NULL,
  type ENUM('vocab', 'small_essay', 'big_essay') NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_section_year_type (year, type),
  CONSTRAINT fk_section_year FOREIGN KEY (year) REFERENCES exam_year (year) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vocab_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  section_id BIGINT UNSIGNED NOT NULL,
  word VARCHAR(128) NOT NULL,
  pos VARCHAR(32) NULL,
  phonetic VARCHAR(128) NULL,
  meaning TEXT NOT NULL,
  word_family TEXT NULL,
  collocation TEXT NULL,
  discrimination TEXT NULL,
  example TEXT NULL,
  example_zh TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  KEY idx_vocab_section (section_id),
  CONSTRAINT fk_vocab_section FOREIGN KEY (section_id) REFERENCES section (id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS essay (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  section_id BIGINT UNSIGNED NOT NULL,
  prompt MEDIUMTEXT NOT NULL,
  draft MEDIUMTEXT NULL,
  revised MEDIUMTEXT NOT NULL,
  notes TEXT NULL,
  video_url VARCHAR(1024) NULL,
  UNIQUE KEY uk_essay_section (section_id),
  CONSTRAINT fk_essay_section FOREIGN KEY (section_id) REFERENCES section (id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS essay_media (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  essay_id BIGINT UNSIGNED NOT NULL,
  kind ENUM('image', 'video', 'draft') NOT NULL DEFAULT 'image',
  mime_type VARCHAR(64) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  data LONGBLOB NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_media_essay (essay_id),
  CONSTRAINT fk_media_essay FOREIGN KEY (essay_id) REFERENCES essay (id) ON DELETE CASCADE
) ENGINE=InnoDB;

INSERT IGNORE INTO exam_year (year)
SELECT y FROM (
  SELECT 2010 AS y UNION ALL SELECT 2011 UNION ALL SELECT 2012 UNION ALL SELECT 2013
  UNION ALL SELECT 2014 UNION ALL SELECT 2015 UNION ALL SELECT 2016 UNION ALL SELECT 2017
  UNION ALL SELECT 2018 UNION ALL SELECT 2019 UNION ALL SELECT 2020 UNION ALL SELECT 2021
  UNION ALL SELECT 2022 UNION ALL SELECT 2023 UNION ALL SELECT 2024 UNION ALL SELECT 2025
  UNION ALL SELECT 2026
) AS years;
